/**
 * Record-time rewriting of business data into `{{reference}}` form.
 *
 * A workflow generated by driving a live page sees REAL values: the keyword
 * that was searched, the name that was typed, the body that was POSTed. If
 * those are recorded as literals the workflow is a one-shot recording — it can
 * only ever repeat the run that produced it. This module replaces each such
 * literal with a reference that resolves at replay time, from one of two
 * sources:
 *
 *   1. **An upstream step produced it.** A `get-text` / `attribute-value` /
 *      `ai-agent` earlier in the same generation wrote the value into a
 *      session variable. The literal is swapped for `{{thatVariable}}`, so the
 *      replay re-reads the page instead of replaying the old text.
 *   2. **It has to come from outside.** Nothing in the graph can produce it
 *      (the user simply said "search for iPhone"), so it becomes a declared
 *      workflow INPUT: the observed literal is kept as the declaration's
 *      `defaultValue` — so the workflow still runs out of the box — and the
 *      parameter references it. The user edits the value on the trigger, and a
 *      trigger payload can override it per run.
 *
 * The literal surviving as a `defaultValue` is deliberate and is NOT the dead
 * data this module exists to remove. Dead data is a value buried inside a
 * step, invisible and unchangeable; a declared input is a labelled, editable,
 * overridable knob that the review card shows before the user saves.
 *
 * ## The case that has no source at all
 *
 * Sources 1 and 2 both assume the value is *legitimately* external. A model
 * that reads the page with its own tools and then pastes the result into a
 * sink block breaks that assumption: the value is neither produced upstream
 * nor something a user would supply, and declaring it an input would disguise
 * a snapshot as a workflow. {@link unproducedBulkData} detects that shape and
 * the operator bridge refuses the call, so the model has to record the step
 * that actually reads the page.
 *
 * Pure functions (no `chrome`, no storage) so the rules are unit-testable and
 * the operator bridge stays the only Chrome-coupled caller.
 *
 * @module lib/workflow/dynamic-data
 */

import { dataValueSites, type DataValueSite } from './data-params'

/** Matches a `{{token}}` reference anywhere in a string. */
const REFERENCE = /\{\{[^{}]*\}\}/

/** Reserved by the interpolation layer: `{{refData}}` means the upstream block. */
const RESERVED_NAMES: ReadonlySet<string> = new Set(['refData'])

/** True when the string already carries a `{{token}}` the engine will resolve. */
export function hasReference(value: string): boolean {
  return REFERENCE.test(value)
}

/**
 * Every `{{token}}` in a string, in order, without the braces.
 *
 * Shares {@link REFERENCE} with {@link hasReference} so "does it reference
 * something" and "what does it reference" can never disagree about what a
 * reference looks like. Used by the save-time integrity check, which has to
 * name each unresolved reference rather than merely notice one exists.
 */
export function referencesIn(value: string): string[] {
  return [...value.matchAll(new RegExp(REFERENCE.source, 'g'))].map((match) =>
    match[0].slice(2, -2),
  )
}

/**
 * What is left of `value` once every `{{token}}` is removed — the part that is
 * a literal no matter what the references resolve to.
 *
 * This exists because a reference used to be an unconditional free pass: the
 * gate skipped any value that contained one. A model that pasted a 1,400-char
 * scraped table and appended a single `{{currentTime}}` (a token nothing in the
 * workflow produces) therefore sailed through, and the saved workflow replayed
 * the generation-time snapshot on every run — precisely the failure the gate is
 * built to stop. Judging the residue instead means "does this reference make the
 * value dynamic?" is answered by what the reference actually covers, not by the
 * mere presence of braces.
 */
export function literalResidue(value: string): string {
  return value.replace(new RegExp(REFERENCE.source, 'g'), '')
}

/**
 * The variable a reference names: everything before the first dot.
 *
 * `{{formsValue.foo}}` reads a property of `formsValue`, so the thing that must
 * exist is `formsValue` — comparing whole paths would report a producer as
 * missing for every property access.
 */
export function referenceRoot(reference: string): string {
  return reference.split('.')[0] ?? reference
}

/**
 * A workflow input the rewrite wants declared.
 *
 * `defaultValue` is the literal observed during generation. It keeps the
 * workflow runnable exactly as generated while staying editable on the trigger.
 */
export interface DeclaredInput {
  name: string
  defaultValue: string
  /** Short provenance note, shown on the review card and in the editor. */
  description: string
  /**
   * True when this input holds a credential captured from a chat-typed literal
   * (e.g. a password field). Carried onto the `WorkflowParameter` so the value
   * is referenceable via `{{name}}` at replay and flagged as secret in the UI.
   */
  secret?: boolean
}

/** One literal → reference swap, reported back to the model. */
export interface DataRewrite {
  path: readonly (string | number)[]
  from: string
  to: string
  /** `'upstream'` when an existing variable held it, `'input'` when declared. */
  via: 'upstream' | 'input'
}

export interface RewriteResult {
  /** The parameters with every business literal replaced. */
  data: Record<string, unknown>
  /** Inputs not declared yet, which the caller must add to the trigger. */
  newInputs: DeclaredInput[]
  rewrites: DataRewrite[]
}

export interface RewriteInput {
  blockId: string
  data: Record<string, unknown>
  /**
   * Literal value → the name of the session variable already holding it
   * (source 1). Built by {@link buildVariableIndex}.
   */
  variableIndex: ReadonlyMap<string, string>
  /**
   * Already-declared input names mapped to their current default (source 2). A
   * literal matching an existing declaration is reused, not declared twice.
   */
  declared: ReadonlyMap<string, string>
  /** The model's suggested name for a new input, when it supplied one. */
  nameHint?: string
  /**
   * Data paths (serialised with `JSON.stringify`) whose literal should be
   * captured as a SECRET input rather than a plain one — used when a credential
   * field is filled with a chat-typed literal that must be persisted in the
   * trigger variable set (and referenced via `{{name}}`) instead of refused.
   */
  secretPaths?: ReadonlySet<string>
}

/**
 * Every non-empty string inside a value tree.
 *
 * Variables hold whatever a block produced — a string today, but rows and
 * objects just as easily — so the index has to see through containers.
 */
function* stringLeavesIn(value: unknown): Generator<string> {
  if (typeof value === 'string') {
    if (value) yield value
    return
  }
  if (Array.isArray(value)) {
    for (const item of value) yield* stringLeavesIn(item)
    return
  }
  if (value !== null && typeof value === 'object') {
    for (const item of Object.values(value as Record<string, unknown>)) {
      yield* stringLeavesIn(item)
    }
  }
}

/**
 * Literal value → the session variable that already holds it.
 *
 * `excludeKeys` keeps credential variables out: a secret is rewritten by
 * `secret-guard` under its own (stricter) rules, and letting this general
 * index claim one first would record a plain variable reference where a
 * credential reference belongs.
 *
 * First name wins when two variables hold the same value: they are
 * interchangeable, and a stable choice keeps the recorded graph tidy.
 */
export function buildVariableIndex(
  variables: Readonly<Record<string, unknown>>,
  excludeKeys: ReadonlySet<string> = new Set(),
): Map<string, string> {
  const byValue = new Map<string, string>()
  for (const [name, value] of Object.entries(variables)) {
    if (excludeKeys.has(name)) continue
    for (const literal of stringLeavesIn(value)) {
      if (!byValue.has(literal)) byValue.set(literal, name)
    }
  }
  return byValue
}

/** Strip anything that cannot appear in a `{{name}}`, and avoid a leading digit. */
function sanitizeName(raw: string): string {
  let name = raw.replace(/[^A-Za-z0-9_]/g, '')
  if (name === '' || /^[0-9]/.test(name)) name = `input${name}`
  if (RESERVED_NAMES.has(name)) name = `${name}Value`
  return name
}

/**
 * Turn a block id + param key into a readable, reference-safe variable name.
 *
 * The result must survive being embedded in `{{...}}`: `getByPath` splits on
 * `.`, so a dot would silently turn a name into a path, and braces would break
 * the token regex outright. Everything outside `[A-Za-z0-9_]` is dropped.
 */
export function inputNameFor(blockId: string, key: string): string {
  const camel = blockId.replace(/[^A-Za-z0-9]+(.)?/g, (_match, char: string) =>
    char ? char.toUpperCase() : '',
  )
  const pascalKey = key.charAt(0).toUpperCase() + key.slice(1)
  return sanitizeName(camel + pascalKey)
}

/**
 * Values never worth parameterising.
 *
 * A checkbox's `value` is `'true'` / `'false'` — that is the CONTROL's state,
 * not business data, and rewriting it would make every checkbox step
 * unreadable. Booleans are the only such case here; numbers are left alone for
 * a different reason (see the module notes on numeric params).
 */
function isRewritable(value: string): boolean {
  if (value.trim() === '') return false
  if (value === 'true' || value === 'false') return false
  return true
}

/** Read the value at `path` inside `root`, or undefined. */
function getAtPath(root: unknown, path: readonly (string | number)[]): unknown {
  let cursor: unknown = root
  for (const segment of path) {
    if (cursor === null || typeof cursor !== 'object') return undefined
    cursor = (cursor as Record<string | number, unknown>)[segment]
  }
  return cursor
}

/** Copy-on-write replacement of one leaf, preserving the original tree. */
function replaceAtPath(node: unknown, path: readonly (string | number)[], next: string): unknown {
  const [head, ...rest] = path
  if (head === undefined) return next
  const source = (node ?? {}) as Record<string | number, unknown>
  const clone = (Array.isArray(source) ? [...(source as unknown[])] : { ...source }) as Record<
    string | number,
    unknown
  >
  clone[head] = rest.length === 0 ? next : replaceAtPath(clone[head], rest, next)
  return clone
}

/**
 * Pick an unused name for a new input.
 *
 * The model's hint wins when it gave one — it knows the value's PURPOSE, so
 * `keyword` beats a derived `newTabUrl`. Otherwise the name comes from the
 * block and parameter, which is predictable if not always pretty; the review
 * card shows every declared input so the user can rename it.
 *
 * A name already taken by a DIFFERENT value gets a numeric suffix rather than
 * stealing the declaration: two inputs sharing a name would silently collapse
 * into one at replay time.
 */
function claimName({
  preferred,
  fallback,
  value,
  declared,
  mintedNames,
}: {
  preferred: string | undefined
  fallback: string
  value: string
  declared: ReadonlyMap<string, string>
  mintedNames: ReadonlySet<string>
}): string {
  const clashes = (name: string): boolean => {
    const existing = declared.get(name)
    if (existing !== undefined) return existing !== value
    return mintedNames.has(name)
  }

  const base = sanitizeName(preferred ?? fallback)
  if (!clashes(base)) return base
  for (let n = 2; n < 100; n += 1) {
    const candidate = `${base}_${n}`
    if (!clashes(candidate)) return candidate
  }
  return `${base}_${mintedNames.size + 1}`
}

/**
 * The most specific NAME in a rewrite path — the last segment that is not an
 * array index.
 *
 * `['conditions', 0, 'right']` names the thing being compared (`right`), not
 * the container, so a derived name reads `conditionsRight` rather than the
 * useless `conditionsConditions`. Likewise a webhook body's leaves become
 * `webhookTitle` / `webhookLevel` instead of all colliding on `webhookBody`.
 */
function lastNamedSegment(path: readonly (string | number)[]): string {
  for (let i = path.length - 1; i >= 0; i -= 1) {
    const segment = path[i]
    if (typeof segment === 'string') return segment
  }
  return 'value'
}

/**
 * Replace every business literal in `data` with a `{{reference}}`.
 *
 * Returns the original object untouched when there is nothing to do, so the
 * common path (structural-only blocks such as `event-click`) allocates
 * nothing.
 */
export function rewriteDataParams(input: RewriteInput): RewriteResult {
  const sites = dataValueSites(input.blockId, input.data)
  if (sites.length === 0) {
    return { data: input.data, newInputs: [], rewrites: [] }
  }

  const newInputs: DeclaredInput[] = []
  const rewrites: DataRewrite[] = []
  /** Literal → name minted during THIS call, so a repeated literal is declared once. */
  const minted = new Map<string, string>()
  const mintedNames = new Set<string>()
  let out: Record<string, unknown> = input.data
  let hintAvailable = input.nameHint !== undefined && input.nameHint !== ''

  for (const site of sites) {
    const { value } = site
    if (hasReference(value)) continue
    if (!isRewritable(value)) continue

    // Source 1: an upstream step already produced this exact value.
    const upstream = input.variableIndex.get(value)
    if (upstream !== undefined) {
      out = replaceAtPath(out, site.path, `{{${upstream}}}`) as Record<string, unknown>
      rewrites.push({ path: site.path, from: value, to: `{{${upstream}}}`, via: 'upstream' })
      continue
    }

    // Source 2: it has to be declared as a workflow input.
    let name = minted.get(value)
    if (name === undefined) {
      name = claimName({
        preferred: hintAvailable ? input.nameHint : undefined,
        fallback: inputNameFor(input.blockId, lastNamedSegment(site.path)),
        value,
        declared: input.declared,
        mintedNames,
      })
      hintAvailable = false
      minted.set(value, name)
      mintedNames.add(name)
      // An existing declaration already defaulting to this literal needs no
      // second declaration — just the reference.
      if (input.declared.get(name) !== value) {
        newInputs.push({
          name,
          defaultValue: value,
          description: `recorded from ${input.blockId}.${lastNamedSegment(site.path)} during generation`,
          ...(input.secretPaths?.has(JSON.stringify(site.path)) ? { secret: true } : {}),
        })
      }
    }
    out = replaceAtPath(out, site.path, `{{${name}}}`) as Record<string, unknown>
    rewrites.push({ path: site.path, from: value, to: `{{${name}}}`, via: 'input' })
  }

  return { data: out, newInputs, rewrites }
}

/**
 * How long a literal may get before it stops looking like a knob and starts
 * looking like content.
 *
 * A trigger field is something a person types: a keyword, a filename, an
 * email, a URL. Nobody types 20 rows of scraped table into one. So a long
 * literal in a data slot is almost always the model pasting what it read off
 * the page itself — which means the graph has no step that reads it, and the
 * saved workflow would re-emit that one snapshot forever.
 */
export const MAX_BULK_LITERAL_CHARS = 400

/**
 * Line count at which a literal reads as a TABLE rather than a template.
 *
 * Set well above the 2-4 lines a multi-line JSON config body or a formatted
 * webhook payload has, because those are legitimate constants and refusing
 * them would be a false positive the model cannot work around.
 */
const MIN_BULK_LINES = 8

/** Shortest multi-line value worth calling tabular; below this it is a snippet. */
const MIN_BULK_MULTILINE_CHARS = 200

/**
 * Does this literal look like CONTENT rather than a user-supplied value?
 *
 * Two independent tells, either sufficient:
 *   - sheer length, which catches a single-line dump of a whole list;
 *   - many lines, which catches a scraped list or CSV pasted in wholesale.
 *
 * Both thresholds are deliberately generous. The gate's job is to catch the
 * obvious shape — a snapshot handed to a sink — not to adjudicate every value;
 * a missed case degrades to the old behaviour, a false positive blocks a
 * legitimate call.
 */
export function looksLikeBulkContent(value: string): boolean {
  if (value.length > MAX_BULK_LITERAL_CHARS) return true
  if (value.length < MIN_BULK_MULTILINE_CHARS) return false
  let newlines = 0
  for (let i = 0; i < value.length; i += 1) {
    if (value.charCodeAt(i) === 10) {
      newlines += 1
      if (newlines >= MIN_BULK_LINES) return true
    }
  }
  return false
}

/**
 * A data literal that nothing in the graph can produce, and that is too big to
 * be a user-supplied knob.
 *
 * This is the signature of the failure this gate exists for: the model reads
 * the page with its OWN tools, composes the answer in its head, and hands the
 * result to a sink block (`save-local` / `insert-data` / `webhook`). The call
 * "succeeds", the rewriter dutifully declares it a workflow input, and the
 * saved workflow contains no step that fetches anything — it replays the
 * generation-time snapshot on every run.
 *
 * Returning the offending site rather than a boolean lets the caller name the
 * exact parameter in the refusal.
 *
 * A site is NOT flagged when an upstream variable already holds the value (a
 * producer ran earlier in the session) or when the parameter is exempt via
 * `allowBulk` (an instruction addressed TO the workflow).
 *
 * What gets judged is the {@link literalResidue} — the part left after every
 * `{{token}}` is removed — not the raw string. A reference only makes a value
 * dynamic to the extent it covers it: `{{hotList}}` is dynamic, but a pasted
 * 1,400-char table with a `{{currentTime}}` appended is a snapshot wearing a
 * reference as a disguise. Skipping such values outright is how a whole frozen
 * scrape used to reach the saved workflow.
 */
export function unproducedBulkData(
  blockId: string,
  data: Record<string, unknown>,
  variableIndex: ReadonlyMap<string, string>,
): DataValueSite | null {
  for (const site of dataValueSites(blockId, data)) {
    if (site.allowBulk) continue
    if (variableIndex.has(site.value)) continue
    const residue = literalResidue(site.value)
    // No literal left at all: the value IS its references. Nothing to freeze.
    if (residue.trim() === '') continue
    if (looksLikeBulkContent(residue)) return site
  }
  return null
}

/**
 * The refusal handed back to the model, naming the exact operators that
 * produce data.
 *
 * Spelling the ladder out is the point: "record the step that reads it" on its
 * own leaves the model guessing WHICH operator, and it will reach for the same
 * shortcut again. The `save-local`-vs-`export-data` distinction is called out
 * because the wrong choice there is what turns a working collector into a file
 * containing one stale row set.
 */
export function unproducedDataRefusal(blockId: string, site: DataValueSite): string {
  const param = lastNamedSegment(site.path)
  return (
    `Refused: \`${blockId}.${param}\` carries ${site.value.length} chars of content that NO step in this workflow produces. ` +
    'A literal like this freezes the snapshot you read just now: the saved workflow would re-emit that same text on every run and never fetch the page again. ' +
    'Appending a `{{reference}}` to pasted text does NOT make it dynamic — the literal part is what gets judged. ' +
    'Record the step that READS the content first, then pass `{{variableName}}`:\n' +
    '  • a repeated list (search results, rankings, table rows) → `wf_op_get-text` with `multiple:true` + `saveData:true` + `dataColumn:"<column>"` — it collects every match into the data table\n' +
    '  • one element\'s text or attribute → `wf_op_get-text` / `wf_op_attribute-value` with `variableName:"<name>"`\n' +
    '  • the whole page, your selection, or its HTML → `wf_op_read-page` with `source:"text"|"selection"|"html"` + `variableName:"<name>"`\n' +
    '  • content that needs interpreting (summarise, classify, reshape) → `wf_op_ai-agent` with `prompt` + `variableName:"<name>"`\n' +
    '  • inside a loop over rows → `wf_op_get-text` with `saveData:true`, one column per iteration (rows are indexed by `loopIndex`)\n' +
    'Write the collected table out with `wf_op_export-data` (`wf_op_save-local` takes a single value, not the table). ' +
    'Retry this call once the producing node exists, referencing it as `{{name}}`. ' +
    '/ 拒绝：这段内容是"你读来的"，工作流里没有任何节点生产它。先记录读取它的算子，再用 {{变量}} 引用。'
  )
}

/** Read the value at a rewrite path out of a data bag. */
export function valueAtRewritePath(
  data: Record<string, unknown>,
  path: readonly (string | number)[],
): unknown {
  return getAtPath(data, path)
}

/**
 * Merge declared inputs into a trigger node's `data`.
 *
 * Exists so the two recording paths cannot drift: operator generation writes
 * the inputs while it builds a draft, the history compiler writes them after
 * the graph already exists. Both go through here, so a workflow input has one
 * shape no matter which path produced it.
 *
 * Names already present are skipped, so re-declaring the same input never
 * duplicates it. Returns the new `data` and the names actually added.
 */
export function mergeTriggerInputs(
  triggerData: Record<string, unknown>,
  inputs: readonly DeclaredInput[],
  known: ReadonlySet<string> = new Set(),
): { data: Record<string, unknown>; added: string[] } {
  if (inputs.length === 0) return { data: triggerData, added: [] }
  const existing: unknown[] = Array.isArray(triggerData['parameters'])
    ? [...(triggerData['parameters'] as unknown[])]
    : []
  const seen = new Set(known)
  const added: string[] = []

  for (const input of inputs) {
    if (seen.has(input.name)) continue
    seen.add(input.name)
    added.push(input.name)
    existing.push({
      // Deterministic id: the name is unique within a workflow, and a stable
      // id keeps the editor's React keys from churning across a worker restart.
      id: `param-${input.name}`,
      name: input.name,
      type: 'string',
      description: input.description,
      // The value observed during generation. Keeps the workflow runnable as
      // generated while remaining editable.
      defaultValue: input.defaultValue,
      placeholder: input.name,
      // A captured credential (chat-typed account/password) is flagged secret
      // so the editor masks it and the run path treats it as a credential.
      ...(input.secret ? { secret: true } : {}),
      data: { required: false },
    })
  }

  if (added.length === 0) return { data: triggerData, added: [] }
  return { data: { ...triggerData, parameters: existing }, added }
}
