import { defineManifest } from '@crxjs/vite-plugin'

/** Flat typing of the crxjs manifest parameter (used to include the MV3 `offscreen` key). */
type ManifestParam = Parameters<typeof defineManifest>[0]

/**
 * MV3 manifest.
 *
 * Permission notes (each one is load-bearing):
 * - `scripting` + broad `host_permissions`: reading the current page works by
 *   injecting a one-off read-only script into the tab the user is looking at.
 *   There is no way to read page text without it.
 * - `tabs`: needed to learn the active tab's URL and title, both to decide
 *   whether it can be read at all and to name it in the approval prompt.
 * - `sidePanel`: the chat lives in a side panel so it survives focus changes and
 *   navigation, unlike a popup, which closes the moment the user clicks the page.
 * - `alarms`: powers scheduled tasks (daily/weekday/interval). An alarm is the
 *   only MV3 mechanism that can wake an idle service worker at a set time, which
 *   a daily 10:00 report fundamentally requires.
 *
 * A static content script is not declared either: page reading injects on demand,
 * which keeps this extension out of every page until the user actually asks it
 * to read one. (The scheduler and Feishu bot run entirely in the service worker
 * and inject nothing into pages unless a task explicitly does.)
 *
 * `icons` and `action.default_icon` are both required. Without them Chrome shows
 * a generic placeholder, which makes a pinned toolbar button impossible to tell
 * apart from any other unbranded extension. Generated by
 * `scripts/generate-icons.mjs`.
 *
 * Paths are `icons/…`, not `public/icons/…`: Vite copies the contents of
 * `public/` to the bundle root, so the directory name is not part of the shipped
 * path. Referencing `public/` here yields a manifest pointing at files that do
 * not exist at that location and Chrome silently falls back to the placeholder.
 */
export default defineManifest({
  manifest_version: 3,
  name: 'Browser Copilot',
  version: '0.5.1',
  description:
    'A side-panel assistant that can read and act on the page you are looking at. Works with any OpenAI-compatible model.',
  minimum_chrome_version: '116',
  permissions: ['storage', 'tabs', 'scripting', 'sidePanel', 'alarms', 'offscreen', 'contextMenus', 'webNavigation', 'cookies', 'downloads', 'clipboardRead', 'debugger'],
  host_permissions: ['http://*/*', 'https://*/*'],
  icons: {
    16: 'icons/icon-16.png',
    32: 'icons/icon-32.png',
    48: 'icons/icon-48.png',
    128: 'icons/icon-128.png',
  },
  background: {
    service_worker: 'src/background/index.ts',
    type: 'module',
  },
  action: {
    default_title: 'Open Browser Copilot',
    default_icon: {
      16: 'icons/icon-16.png',
      32: 'icons/icon-32.png',
      48: 'icons/icon-48.png',
      128: 'icons/icon-128.png',
    },
  },
  side_panel: {
    default_path: 'src/sidepanel/index.html',
  },
  offscreen: {
    document_url: 'src/offscreen/index.html',
    justification:
      'Used by the clipboard workflow block to read/write the system clipboard without disturbing the active page.',
  },
} as unknown as ManifestParam)
