import { defineManifest } from '@crxjs/vite-plugin'
import type { ConfigEnv } from 'vite'

/** Release version — single source for both variant manifests. */
const VERSION = '0.6.0'

/** Flat typing of the crxjs manifest parameter (some fields below are wider than the typed union allows). */
type ManifestParam = Parameters<typeof defineManifest>[0]

/**
 * MV3 manifest.
 *
 * Permission notes (each one is load-bearing):
 * - `scripting` + broad `host_permissions`: reading the current page works by
 *   injecting a one-off read-only script into the tab the user is looking at.
 *   There is no way to read page text without it.
 * - `tabs`: needed to learn the active tab's URL and title, both to decide
 *   whether it can be read at all and to name it in the approval prompt.
 * - `sidePanel`: the chat lives in a side panel so it survives focus changes and
 *   navigation, unlike a popup, which closes the moment the user clicks the page.
 * - `alarms`: powers scheduled tasks (daily/weekday/interval). An alarm is the
 *   only MV3 mechanism that can wake an idle service worker at a set time, which
 *   a daily 10:00 report fundamentally requires.
 *
 * One static content script IS declared (see `content_scripts` below): it only
 * parks the in-page kernel on each frame and is inert until an op arrives, so
 * the extension still reads and acts on a page only when the user asks it to.
 * (The scheduler and Feishu bot run entirely in the service worker and inject
 * nothing into pages unless a task explicitly does.)
 *
 * `icons` and `action.default_icon` are both required. Without them Chrome shows
 * a generic placeholder, which makes a pinned toolbar button impossible to tell
 * apart from any other unbranded extension. Generated by
 * `scripts/generate-icons.mjs`.
 *
 * Paths are `icons/…`, not `public/icons/…`: Vite copies the contents of
 * `public/` to the bundle root, so the directory name is not part of the shipped
 * path. Referencing `public/` here yields a manifest pointing at files that do
 * not exist at that location and Chrome silently falls back to the placeholder.
 */
/**
 * Release variants (see vite.config.ts): the default build ships local OCR
 * (Tesseract.js), while `--mode no-ocr` produces the lite release:
 * - CSP drops `'wasm-unsafe-eval'` — nothing compiles WebAssembly anymore.
 * - `version_name` marks the variant so the two builds are distinguishable in
 *   chrome://extensions.
 * - The vendored public/tesseract/ assets are stripped by the build itself.
 */
export default defineManifest(((env: ConfigEnv) => {
  const ocr = env.mode !== 'no-ocr'
  return {
  manifest_version: 3,
  name: 'Browser Copilot',
  version: VERSION,
  // Marks the lite build in chrome://extensions (the numeric `version` stays
  // identical so both variants track the same release).
  ...(ocr ? {} : { version_name: `${VERSION} (no OCR)` }),
  description:
    'A side-panel assistant that can read and act on the page you are looking at. Works with any OpenAI-compatible model.',
  minimum_chrome_version: '116',
  permissions: ['storage', 'tabs', 'scripting', 'sidePanel', 'alarms', 'offscreen', 'contextMenus', 'webNavigation', 'cookies', 'downloads', 'clipboardRead', 'debugger'],
  // '<all_urls>' is load-bearing for screenshots: chrome.tabs.captureVisibleTab
  // hard-requires it (or activeTab) and rejects equivalent-looking specific
  // patterns — 'http://*/*' + 'https://*/*' alone fail with "Either the
  // '<all_urls>' or 'activeTab' permission is required." activeTab cannot
  // replace it here: its grant is user-gesture-bound and revoked on
  // navigation, while the agent screenshots pages it has just driven to.
  // The http/https/ws patterns are kept below only for readability;
  // '<all_urls>' already covers them.
  host_permissions: ['<all_urls>', 'http://*/*', 'https://*/*', 'ws://localhost/*', 'ws://127.0.0.1/*', 'ws://[::1]/*'],
  // Local OCR (Tesseract.js in the offscreen document) needs to compile the
  // bundled WebAssembly core. `'wasm-unsafe-eval'` permits that while keeping
  // `script-src 'self'` — no JS eval. The vendored core is fetched from the
  // extension origin, and the worker is created directly from that URL (no blob).
  // The no-ocr build has no wasm at all, so the grant is dropped entirely.
  content_security_policy: {
    extension_pages: ocr
      ? "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'"
      : "script-src 'self'; object-src 'self'",
  },
  icons: {
    16: 'icons/icon-16.png',
    32: 'icons/icon-32.png',
    48: 'icons/icon-48.png',
    128: 'icons/icon-128.png',
  },
  background: {
    service_worker: 'src/background/index.ts',
    type: 'module',
  },
  // The in-page kernel host (see src/inpage/content-kernel.ts). Previously the
  // driver re-serialized the whole kernel into every op; now this script parks
  // it on each frame at document_idle and ops ship only their arguments. It
  // stays passive until the user triggers an action, so the privacy posture of
  // the on-demand injection it replaces is unchanged.
  content_scripts: [
    {
      matches: ['http://*/*', 'https://*/*'],
      js: ['src/inpage/content-kernel.ts'],
      all_frames: true,
      run_at: 'document_idle',
    },
    {
      // Floating "restore" button for the minimized plugin. Renders nothing
      // unless the service worker reports this window minimized (see
      // src/inpage/floating-button.ts). Main frame only: one button per page.
      matches: ['http://*/*', 'https://*/*'],
      js: ['src/inpage/floating-button.ts'],
      all_frames: false,
      run_at: 'document_idle',
    },
  ],
  // The floating button loads the extension icon inside web pages; without
  // this declaration Chrome blocks the chrome-extension:// fetch.
  web_accessible_resources: [
    {
      resources: ['icons/icon-48.png'],
      matches: ['http://*/*', 'https://*/*'],
    },
  ],
  action: {
    default_title: 'Open Browser Copilot',
    default_icon: {
      16: 'icons/icon-16.png',
      32: 'icons/icon-32.png',
      48: 'icons/icon-48.png',
      128: 'icons/icon-128.png',
    },
  },
  side_panel: {
    default_path: 'src/sidepanel/index.html',
  },
  }
}) as unknown as ManifestParam)
