/**
 * AUTO-GENERATED by src/lib/workflow/blocks/catalog.gen.mjs - do not edit by hand.
 * Source: automa/src/utils/shared.js (tasks + categories).
 * Re-run `node src/lib/workflow/blocks/catalog.gen.mjs` after updating Automa.
 *
 * @module lib/workflow/blocks/catalog
 */

import type { BlockCatalogEntry, AutomaCategory, CategoryMeta } from './types'

export const CATEGORY_META: Record<AutomaCategory, CategoryMeta> = {
  "interaction": {
    "name": "Web interaction",
    "light": {
      "bg": "#bbf7d0",
      "border": "#bbf7d0"
    },
    "dark": {
      "bg": "#86efac",
      "border": "#86efac"
    }
  },
  "browser": {
    "name": "Browser",
    "light": {
      "bg": "#fed7aa",
      "border": "#fed7aa"
    },
    "dark": {
      "bg": "#fdba74",
      "border": "#fdba74"
    }
  },
  "general": {
    "name": "General",
    "light": {
      "bg": "#fef08a",
      "border": "#fef08a"
    },
    "dark": {
      "bg": "#fde047",
      "border": "#fde047"
    }
  },
  "onlineServices": {
    "name": "Online services",
    "light": {
      "bg": "#fecaca",
      "border": "#fecaca"
    },
    "dark": {
      "bg": "#fca5a5",
      "border": "#fca5a5"
    }
  },
  "data": {
    "name": "Data",
    "light": {
      "bg": "#d9f99d",
      "border": "#d9f99d"
    },
    "dark": {
      "bg": "#bef264",
      "border": "#bef264"
    }
  },
  "conditions": {
    "name": "Control flow",
    "light": {
      "bg": "#bfdbfe",
      "border": "#bfdbfe"
    },
    "dark": {
      "bg": "#93c5fd",
      "border": "#93c5fd"
    }
  },
  "package": {
    "name": "Packages",
    "light": {
      "bg": "#a5f3fc",
      "border": "#a5f3fc"
    },
    "dark": {
      "bg": "#67e8f9",
      "border": "#67e8f9"
    }
  }
}

export const BLOCK_CATALOG: BlockCatalogEntry[] = [
  {
    "id": "trigger",
    "name": "Trigger",
    "description": "Block where workflow will start executing",
    "icon": "riFlashlightLine",
    "component": "BlockBasic",
    "editComponent": "EditTrigger",
    "category": "general",
    "inputs": 0,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "url"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "type": "manual",
      "interval": 60,
      "delay": 5,
      "date": "",
      "time": "00:00",
      "url": "",
      "shortcut": "",
      "activeInInput": false,
      "isUrlRegex": false,
      "days": [],
      "contextMenuName": "",
      "contextTypes": [],
      "parameters": [],
      "preferParamsInTab": false,
      "observeElement": {
        "selector": "",
        "baseSelector": "",
        "matchPattern": "",
        "targetOptions": {
          "subtree": false,
          "childList": true,
          "attributes": false,
          "attributeFilter": [],
          "characterData": false
        },
        "baseElOptions": {
          "subtree": false,
          "childList": true,
          "attributes": false,
          "attributeFilter": [],
          "characterData": false
        }
      }
    },
    "cloud": false
  },
  {
    "id": "ai-workflow",
    "name": "AI Workflow",
    "description": "A workflow that is created by AI-Power",
    "icon": "https://winrobot-pub-a-1302949341.cos.ap-shanghai.myqcloud.com/image/20250717194249/10e0c06a7b243d15ac9a9385b07ce4e2.svg",
    "component": "BlockBasic",
    "editComponent": "EditAiWorkflow",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "tag": "AI",
    "data": {
      "disableBlock": false,
      "flowUuid": "",
      "flowLabel": "",
      "description": "",
      "inputs": [],
      "outputs": [],
      "assignVariable": false,
      "variableName": "",
      "saveData": false,
      "dataColumn": ""
    },
    "cloud": true
  },
  {
    "id": "execute-workflow",
    "name": "Execute workflow",
    "description": "",
    "icon": "riFlowChart",
    "component": "BlockBasic",
    "editComponent": "EditExecuteWorkflow",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "globalData"
    ],
    "data": {
      "disableBlock": false,
      "executeId": "",
      "workflowId": "",
      "globalData": "",
      "description": "",
      "insertAllVars": false,
      "insertAllGlobalData": false
    },
    "cloud": false
  },
  {
    "id": "active-tab",
    "name": "Active tab",
    "description": "Set current tab that you're in as an active tab",
    "icon": "riWindowLine",
    "component": "BlockBasic",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "disableEdit": true,
    "data": {
      "disableBlock": false
    },
    "cloud": false
  },
  {
    "id": "new-tab",
    "name": "New tab",
    "description": "Create a new tab",
    "icon": "riGlobalLine",
    "component": "BlockBasic",
    "editComponent": "EditNewTab",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "url",
      "userAgent"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "url": "",
      "userAgent": "",
      "active": true,
      "tabZoom": 1,
      "inGroup": false,
      "waitTabLoaded": false,
      "updatePrevTab": false,
      "customUserAgent": false
    },
    "cloud": false
  },
  {
    "id": "switch-tab",
    "name": "Switch tab",
    "description": "Switch active tab",
    "icon": "riArrowLeftRightLine",
    "component": "BlockBasic",
    "editComponent": "EditSwitchTab",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "url",
      "matchPattern",
      "tabTitle"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "url": "",
      "tabIndex": 0,
      "tabTitle": "",
      "matchPattern": "",
      "activeTab": true,
      "createIfNoMatch": false,
      "findTabBy": "match-patterns"
    },
    "cloud": false
  },
  {
    "id": "new-window",
    "name": "New window",
    "description": "Create a new window",
    "icon": "riWindow2Line",
    "component": "BlockBasic",
    "editComponent": "EditNewWindow",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "url"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "top": 0,
      "left": 0,
      "width": 0,
      "url": "",
      "height": 0,
      "type": "normal",
      "incognito": false,
      "windowState": "normal"
    },
    "cloud": false
  },
  {
    "id": "proxy",
    "name": "Proxy",
    "description": "Set the proxy of the browser",
    "icon": "riShieldKeyholeLine",
    "component": "BlockBasic",
    "editComponent": "EditProxy",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "host",
      "port",
      "scheme"
    ],
    "data": {
      "description": "",
      "disableBlock": false,
      "scheme": "https",
      "host": "",
      "port": 443,
      "bypassList": "",
      "clearProxy": false
    },
    "cloud": false
  },
  {
    "id": "go-back",
    "name": "Go back",
    "description": "Go back to the previous page",
    "icon": "riArrowGoBackLine",
    "component": "BlockBasic",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "disableEdit": true,
    "data": {
      "disableBlock": false
    },
    "cloud": false
  },
  {
    "id": "forward-page",
    "name": "Go forward",
    "description": "Go forward to the next page",
    "icon": "riArrowGoForwardLine",
    "component": "BlockBasic",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "disableEdit": true,
    "data": {
      "disableBlock": false
    },
    "cloud": false
  },
  {
    "id": "close-tab",
    "name": "Close tab/window",
    "icon": "riCloseCircleLine",
    "component": "BlockBasic",
    "editComponent": "EditCloseTab",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "url"
    ],
    "data": {
      "disableBlock": false,
      "url": "",
      "description": "",
      "activeTab": true,
      "closeType": "tab",
      "allWindows": false
    },
    "description": "",
    "cloud": false
  },
  {
    "id": "take-screenshot",
    "name": "Take screenshot",
    "description": "Take a screenshot of current active tab",
    "icon": "riImageLine",
    "component": "BlockBasic",
    "editComponent": "EditTakeScreenshot",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "fileName",
      "selector",
      "variableName"
    ],
    "data": {
      "description": "",
      "disableBlock": false,
      "fileName": "",
      "ext": "png",
      "quality": 100,
      "dataColumn": "",
      "variableName": "",
      "selector": "",
      "fullPage": false,
      "saveToColumn": false,
      "saveToComputer": true,
      "assignVariable": false,
      "captureActiveTab": true
    },
    "cloud": false
  },
  {
    "id": "browser-event",
    "name": "Browser event",
    "description": "Wait until the selected event is triggered",
    "icon": "riLightbulbLine",
    "component": "BlockBasic",
    "editComponent": "EditBrowserEvent",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "timeout": 10000,
      "eventName": "tab:loaded",
      "setAsActiveTab": true,
      "activeTabLoaded": true,
      "tabLoadedUrl": "",
      "tabUrl": "",
      "fileQuery": ""
    },
    "cloud": false
  },
  {
    "id": "event-click",
    "name": "Click element",
    "icon": "riCursorLine",
    "component": "BlockBasic",
    "editComponent": "EditInteractionBase",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "markEl": false,
      "multiple": false
    },
    "description": "",
    "cloud": false
  },
  {
    "id": "delay",
    "name": "Delay",
    "description": "Add delay before executing the next block",
    "icon": "riTimerLine",
    "component": "BlockDelay",
    "editComponent": "EditDelay",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "time"
    ],
    "data": {
      "disableBlock": false,
      "time": 500
    },
    "cloud": false
  },
  {
    "id": "get-text",
    "name": "Get text",
    "description": "Get text from an element",
    "icon": "riParagraph",
    "component": "BlockBasic",
    "editComponent": "EditGetText",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector",
      "variableName",
      "prefixText",
      "suffixText",
      "extraRowValue"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "markEl": false,
      "multiple": false,
      "regex": "",
      "prefixText": "",
      "suffixText": "",
      "regexExp": [],
      "dataColumn": "",
      "saveData": true,
      "includeTags": false,
      "addExtraRow": false,
      "assignVariable": false,
      "useTextContent": false,
      "variableName": "",
      "extraRowValue": "",
      "extraRowDataColumn": ""
    },
    "cloud": false
  },
  {
    "id": "export-data",
    "name": "Export data",
    "icon": "riDownloadLine",
    "component": "BlockBasic",
    "editComponent": "EditExportData",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "name",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "name": "",
      "refKey": "",
      "type": "json",
      "description": "",
      "variableName": "",
      "csvDelimiter": ",",
      "addBOMHeader": true,
      "onConflict": "uniquify",
      "dataToExport": "data-columns"
    },
    "description": "",
    "cloud": false
  },
  {
    "id": "element-scroll",
    "name": "Scroll element",
    "icon": "riMouseLine",
    "component": "BlockBasic",
    "editComponent": "EditScrollElement",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "html",
      "markEl": false,
      "multiple": false,
      "scrollY": 0,
      "scrollX": 0,
      "incX": false,
      "incY": false,
      "smooth": false,
      "scrollIntoView": false
    },
    "description": "",
    "cloud": false
  },
  {
    "id": "link",
    "name": "Link",
    "description": "Open link element",
    "icon": "riLink",
    "component": "BlockBasic",
    "editComponent": "EditLink",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "markEl": false,
      "disableMultiple": true,
      "openInNewTab": false
    },
    "cloud": false
  },
  {
    "id": "attribute-value",
    "name": "Attribute value",
    "description": "Get attribute value of an element",
    "icon": "riBracketsLine",
    "component": "BlockBasic",
    "editComponent": "EditAttributeValue",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector",
      "variableName",
      "attributeName",
      "extraRowValue",
      "attributeValue"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "markEl": false,
      "multiple": false,
      "attributeValue": "",
      "attributeName": "",
      "assignVariable": false,
      "variableName": "",
      "dataColumn": "",
      "saveData": true,
      "action": "get",
      "addExtraRow": false,
      "extraRowValue": "",
      "extraRowDataColumn": ""
    },
    "cloud": false
  },
  {
    "id": "forms",
    "name": "Forms",
    "description": "Manipulate form(input, select, checkbox, and radio) element",
    "icon": "riInputCursorMove",
    "component": "BlockBasic",
    "editComponent": "EditForms",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector",
      "variableName",
      "value",
      "optionPosition",
      "delay"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "markEl": false,
      "multiple": false,
      "selected": true,
      "clearValue": true,
      "getValue": false,
      "saveData": false,
      "dataColumn": "",
      "selectOptionBy": "value",
      "optionPosition": "1",
      "assignVariable": false,
      "variableName": "",
      "type": "text-field",
      "value": "",
      "delay": 0,
      "events": []
    },
    "cloud": false
  },
  {
    "id": "repeat-task",
    "name": "Repeat task",
    "icon": "riRepeat2Line",
    "component": "BlockRepeatTask",
    "category": "conditions",
    "inputs": 1,
    "outputs": 2,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "repeatFor"
    ],
    "data": {
      "disableBlock": false,
      "repeatFor": "1"
    },
    "description": "",
    "cloud": false
  },
  {
    "id": "javascript-code",
    "name": "JavaScript code",
    "description": "Execute your custom javascript code in a webpage",
    "icon": "riCodeSSlashLine",
    "component": "BlockBasic",
    "editComponent": "EditJavascriptCode",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "timeout": 20000,
      "context": "website",
      "code": "console.log(\"Hello world!\");\nautomaNextBlock()",
      "preloadScripts": [],
      "everyNewTab": false,
      "runBeforeLoad": false
    },
    "cloud": false
  },
  {
    "id": "trigger-event",
    "name": "Trigger event",
    "description": "Trigger event",
    "icon": "riLightbulbFlashLine",
    "component": "BlockBasic",
    "editComponent": "EditTriggerEvent",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector",
      "eventParams.clientX",
      "eventParams.clientY"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "html",
      "markEl": false,
      "multiple": false,
      "eventName": "",
      "eventType": "",
      "eventParams": {
        "bubbles": true,
        "cancelable": false
      }
    },
    "cloud": false
  },
  {
    "id": "google-sheets",
    "name": "Google sheets",
    "description": "Read Google Sheets data",
    "icon": "mdiGoogleSheet",
    "component": "BlockBasic",
    "editComponent": "EditGoogleSheets",
    "category": "onlineServices",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "customData",
      "range",
      "spreadsheetId",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "range": "",
      "refKey": "",
      "type": "get",
      "customData": "",
      "description": "",
      "spreadsheetId": "",
      "dataColumn": "",
      "saveData": true,
      "assignVariable": false,
      "variableName": "",
      "firstRowAsKey": false,
      "keysAsFirstRow": true,
      "valueInputOption": "RAW",
      "InsertDataOption": "INSERT_ROWS",
      "dataFrom": "data-columns"
    },
    "cloud": true
  },
  {
    "id": "google-sheets-drive",
    "name": "Google sheets (GDrive)",
    "description": "Read Google Sheets data",
    "icon": "riDriveFill",
    "component": "BlockBasic",
    "editComponent": "EditGoogleSheetsDrive",
    "category": "onlineServices",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "customData",
      "range",
      "spreadsheetId",
      "sheetName",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "range": "",
      "refKey": "",
      "type": "get",
      "customData": "",
      "description": "",
      "spreadsheetId": "",
      "dataColumn": "",
      "inputSpreadsheetId": "connected",
      "saveData": true,
      "sheetName": "",
      "assignVariable": false,
      "variableName": "",
      "firstRowAsKey": false,
      "keysAsFirstRow": true,
      "valueInputOption": "RAW",
      "InsertDataOption": "INSERT_ROWS",
      "dataFrom": "data-columns"
    },
    "cloud": true
  },
  {
    "id": "google-drive",
    "name": "Google drive",
    "description": "Upload files to Google Drive",
    "icon": "riDriveLine",
    "component": "BlockBasic",
    "editComponent": "EditGoogleDrive",
    "category": "onlineServices",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [],
    "data": {
      "disableBlock": false,
      "action": "upload",
      "filePaths": []
    },
    "cloud": true
  },
  {
    "id": "conditions",
    "name": "Conditions",
    "description": "Conditional block",
    "icon": "riAB",
    "component": "BlockConditions",
    "editComponent": "EditConditions",
    "category": "conditions",
    "inputs": 1,
    "outputs": 0,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "description": "",
      "disableBlock": false,
      "conditions": [],
      "retryConditions": false,
      "retryCount": 10,
      "retryTimeout": 1000
    },
    "cloud": false
  },
  {
    "id": "element-exists",
    "name": "Element exists",
    "description": "Check if an element is exists",
    "icon": "riFocus3Line",
    "component": "BlockElementExists",
    "editComponent": "EditElementExists",
    "category": "conditions",
    "inputs": 1,
    "outputs": 2,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "selector": "",
      "tryCount": 1,
      "timeout": 500,
      "markEl": false,
      "throwError": false
    },
    "cloud": false
  },
  {
    "id": "webhook",
    "name": "HTTP Request",
    "description": "make an HTTP request",
    "icon": "riEarthLine",
    "component": "BlockBasicWithFallback",
    "editComponent": "EditWebhook",
    "category": "general",
    "inputs": 1,
    "outputs": 2,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "body",
      "url",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "url": "",
      "body": "{}",
      "headers": [],
      "method": "POST",
      "timeout": 10000,
      "dataPath": "",
      "contentType": "json",
      "variableName": "",
      "assignVariable": false,
      "saveData": false,
      "dataColumn": "",
      "responseType": "json"
    },
    "cloud": false
  },
  {
    "id": "while-loop",
    "name": "While loop",
    "description": "Execute blocks while the condition is met",
    "icon": "riRefreshFill",
    "component": "BlockBasicWithFallback",
    "editComponent": "EditWhileLoop",
    "category": "conditions",
    "inputs": 1,
    "outputs": 2,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "conditions": null
    },
    "cloud": false
  },
  {
    "id": "loop-data",
    "name": "Loop data",
    "icon": "riRefreshLine",
    "component": "BlockBasic",
    "editComponent": "EditLoopData",
    "category": "conditions",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "maxLoop",
      "loopData",
      "selector",
      "startIndex",
      "variableName",
      "referenceKey",
      "elementSelector"
    ],
    "data": {
      "disableBlock": false,
      "loopId": "",
      "maxLoop": 0,
      "toNumber": 10,
      "fromNumber": 1,
      "startIndex": 0,
      "loopData": "[]",
      "description": "",
      "variableName": "",
      "referenceKey": "",
      "reverseLoop": false,
      "elementSelector": "",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "resumeLastWorkflow": false,
      "loopThrough": "data-columns"
    },
    "description": "",
    "cloud": false
  },
  {
    "id": "loop-elements",
    "name": "Loop elements",
    "icon": "riRestartLine",
    "component": "BlockBasic",
    "editComponent": "EditLoopElements",
    "category": "conditions",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "maxLoop",
      "selector",
      "variableName",
      "elementSelector",
      "actionElSelector"
    ],
    "data": {
      "disableBlock": false,
      "loopId": "",
      "selector": "",
      "maxLoop": "0",
      "description": "",
      "reverseLoop": false,
      "actionElSelector": "",
      "findBy": "cssSelector",
      "actionElMaxWaitTime": 5,
      "actionPageMaxWaitTime": 10,
      "loadMoreAction": "none",
      "scrollToBottom": true,
      "waitForSelector": false,
      "waitSelectorTimeout": 5000
    },
    "description": "",
    "cloud": false
  },
  {
    "id": "loop-breakpoint",
    "name": "Loop breakpoint",
    "description": "To tell where loop data must stop",
    "icon": "riStopLine",
    "component": "BlockLoopBreakpoint",
    "category": "conditions",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "disableEdit": true,
    "data": {
      "disableBlock": false,
      "loopId": "",
      "clearLoop": false
    },
    "cloud": false
  },
  {
    "id": "blocks-group",
    "name": "Blocks group",
    "description": "Grouping blocks",
    "icon": "riFolderZipLine",
    "component": "BlockGroup",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "disableEdit": true,
    "data": {
      "disableBlock": false,
      "name": "",
      "blocks": []
    },
    "cloud": false
  },
  {
    "id": "clipboard",
    "name": "Clipboard",
    "description": "Get the copied text from the clipboard",
    "icon": "riClipboardLine",
    "component": "BlockBasic",
    "editComponent": "EditClipboard",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "dataToCopy",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "type": "get",
      "assignVariable": false,
      "variableName": "",
      "saveData": true,
      "dataColumn": "",
      "dataToCopy": "",
      "copySelectedText": false
    },
    "cloud": false
  },
  {
    "id": "insert-data",
    "name": "Insert data",
    "description": "Insert data into table or variable",
    "icon": "riDatabase2Line",
    "component": "BlockBasic",
    "editComponent": "EditInsertData",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "dataList": []
    },
    "cloud": false
  },
  {
    "id": "switch-to",
    "name": "Switch frame",
    "description": "Switch between main window and iframe",
    "icon": "riArrowUpDownLine",
    "component": "BlockBasic",
    "editComponent": "EditSwitchTo",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector"
    ],
    "data": {
      "disableBlock": false,
      "findBy": "cssSelector",
      "selector": "",
      "windowType": "main-window"
    },
    "cloud": false
  },
  {
    "id": "upload-file",
    "name": "Upload file",
    "description": "Upload file into <input type=\"file\"> element",
    "icon": "riFileUploadLine",
    "component": "BlockBasic",
    "editComponent": "EditUploadFile",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector",
      "filePaths"
    ],
    "data": {
      "disableBlock": false,
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "filePaths": []
    },
    "cloud": false
  },
  {
    "id": "hover-element",
    "name": "Hover element",
    "description": "Hover over an element",
    "icon": "path:M11.5,11L17.88,16.37L17,16.55L16.36,16.67C15.73,16.8 15.37,17.5 15.65,18.07L15.92,18.65L17.28,21.59L15.86,22.25L14.5,19.32L14.24,18.74C13.97,18.15 13.22,17.97 12.72,18.38L12.21,18.78L11.5,19.35V11M10.76,8.69A0.76,0.76 0 0,0 10,9.45V20.9C10,21.32 10.34,21.66 10.76,21.66C10.95,21.66 11.11,21.6 11.24,21.5L13.15,19.95L14.81,23.57C14.94,23.84 15.21,24 15.5,24C15.61,24 15.72,24 15.83,23.92L18.59,22.64C18.97,22.46 19.15,22 18.95,21.63L17.28,18L19.69,17.55C19.85,17.5 20,17.43 20.12,17.29C20.39,16.97 20.35,16.5 20,16.21L11.26,8.86L11.25,8.87C11.12,8.76 10.95,8.69 10.76,8.69M15,10V8H20V10H15M13.83,4.76L16.66,1.93L18.07,3.34L15.24,6.17L13.83,4.76M10,0H12V5H10V0M3.93,14.66L6.76,11.83L8.17,13.24L5.34,16.07L3.93,14.66M3.93,3.34L5.34,1.93L8.17,4.76L6.76,6.17L3.93,3.34M7,10H2V8H7V10",
    "component": "BlockBasic",
    "editComponent": "EditInteractionBase",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "markEl": false,
      "multiple": false
    },
    "cloud": false
  },
  {
    "id": "save-assets",
    "name": "Save assets",
    "description": "Save assets (image, video, audio, or file) from an element or URL",
    "icon": "riImageLine",
    "component": "BlockBasic",
    "editComponent": "EditSaveAssets",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector",
      "url",
      "filename",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "findBy": "cssSelector",
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "",
      "markEl": false,
      "multiple": false,
      "type": "element",
      "url": "",
      "filename": "",
      "saveDownloadIds": false,
      "onConflict": "uniquify",
      "dataColumn": "",
      "saveData": true,
      "assignVariable": false,
      "variableName": "",
      "saveToGDrive": false
    },
    "cloud": false
  },
  {
    "id": "press-key",
    "name": "Press key",
    "description": "Press a key or a combination",
    "icon": "riKeyboardLine",
    "component": "BlockBasic",
    "editComponent": "EditPressKey",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "selector",
      "keys",
      "keysToPress",
      "pressTime"
    ],
    "data": {
      "disableBlock": false,
      "keys": "",
      "selector": "",
      "pressTime": "0",
      "description": "",
      "keysToPress": "",
      "action": "press-key"
    },
    "cloud": false
  },
  {
    "id": "handle-dialog",
    "name": "Handle dialog",
    "description": "Accepts or dismisses a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload).",
    "icon": "riChat3Line",
    "component": "BlockBasic",
    "editComponent": "EditHandleDialog",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "promptText"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "accept": true,
      "promptText": ""
    },
    "cloud": false
  },
  {
    "id": "handle-download",
    "name": "Handle download",
    "description": "Handle downloaded file",
    "icon": "riFileDownloadLine",
    "component": "BlockBasic",
    "editComponent": "EditHandleDownload",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "filename",
      "downloadId",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "filename": "",
      "timeout": 20000,
      "onConflict": "uniquify",
      "waitForDownload": true,
      "dataColumn": "",
      "saveData": true,
      "assignVariable": false,
      "variableName": "",
      "downloadId": ""
    },
    "cloud": false
  },
  {
    "id": "reload-tab",
    "name": "Reload tab",
    "description": "Reload the active tab",
    "icon": "riRestartLine",
    "component": "BlockBasic",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "disableEdit": true,
    "data": {
      "disableBlock": false
    },
    "cloud": false
  },
  {
    "id": "delete-data",
    "name": "Delete data",
    "description": "Delete table or variable data",
    "icon": "riDeleteBin7Line",
    "component": "BlockBasic",
    "editComponent": "EditDeleteData",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "deleteList": []
    },
    "cloud": false
  },
  {
    "id": "wait-connections",
    "name": "Wait connections",
    "description": "Wait for all connections before continuing to the next block",
    "icon": "riTimerFlashLine",
    "component": "BlockBasic",
    "editComponent": "EditWaitConnections",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "timeout": 10000,
      "specificFlow": false,
      "flowBlockId": ""
    },
    "cloud": false
  },
  {
    "id": "notification",
    "name": "Notification",
    "description": "Display a notification",
    "icon": "riNotification3Line",
    "component": "BlockBasic",
    "editComponent": "EditNotification",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "message",
      "title",
      "iconUrl",
      "imageUrl"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "message": "",
      "iconUrl": "",
      "imageUrl": "",
      "title": "Hello world!"
    },
    "cloud": false
  },
  {
    "id": "log-data",
    "name": "Get log data",
    "description": "Get the latest log data of a workflow",
    "icon": "riFileHistoryLine",
    "component": "BlockBasic",
    "editComponent": "EditLogData",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "workflowId": "",
      "dataColumn": "",
      "saveData": true,
      "assignVariable": false,
      "variableName": ""
    },
    "cloud": false
  },
  {
    "id": "tab-url",
    "name": "Get tab URL",
    "description": "Get the tab URL",
    "icon": "riLinksLine",
    "component": "BlockBasic",
    "editComponent": "EditTabURL",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "type": "active-tab",
      "dataColumn": "",
      "saveData": true,
      "assignVariable": false,
      "variableName": "",
      "qTitle": "",
      "qMatchPatterns": ""
    },
    "cloud": false
  },
  {
    "id": "slice-variable",
    "name": "Slice variable",
    "description": "Extracts a section of a variable value",
    "icon": "riSliceLine",
    "component": "BlockBasic",
    "editComponent": "EditSliceVariable",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "endIdxEnabled": false,
      "startIdxEnabled": true,
      "endIndex": 0,
      "startIndex": 0,
      "variableName": ""
    },
    "cloud": false
  },
  {
    "id": "increase-variable",
    "name": "Increase variable",
    "description": "Increase the value of a variable by specific amount",
    "icon": "riIncreaseDecreaseLine",
    "component": "BlockBasic",
    "editComponent": "EditIncreaseVariable",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "increaseBy": 1,
      "variableName": ""
    },
    "cloud": false
  },
  {
    "id": "regex-variable",
    "name": "RegEx variable",
    "description": "Matching a variable value against a regular expression",
    "icon": "path:M16,16.92C15.67,16.97 15.34,17 15,17C14.66,17 14.33,16.97 14,16.92V13.41L11.5,15.89C11,15.5 10.5,15 10.11,14.5L12.59,12H9.08C9.03,11.67 9,11.34 9,11C9,10.66 9.03,10.33 9.08,10H12.59L10.11,7.5C10.3,7.25 10.5,7 10.76,6.76V6.76C11,6.5 11.25,6.3 11.5,6.11L14,8.59V5.08C14.33,5.03 14.66,5 15,5C15.34,5 15.67,5.03 16,5.08V8.59L18.5,6.11C19,6.5 19.5,7 19.89,7.5L17.41,10H20.92C20.97,10.33 21,10.66 21,11C21,11.34 20.97,11.67 20.92,12H17.41L19.89,14.5C19.7,14.75 19.5,15 19.24,15.24V15.24C19,15.5 18.75,15.7 18.5,15.89L16,13.41V16.92H16V16.92M5,19A2,2 0 0,1 7,17A2,2 0 0,1 9,19A2,2 0 0,1 7,21A2,2 0 0,1 5,19H5Z",
    "component": "BlockBasic",
    "editComponent": "EditRegexVariable",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "replaceVal"
    ],
    "data": {
      "disableBlock": false,
      "method": "match",
      "replaceVal": "",
      "description": "",
      "expression": "",
      "flag": []
    },
    "cloud": false
  },
  {
    "id": "data-mapping",
    "name": "Data mapping",
    "description": "Map data of a variable or table",
    "icon": "riMindMap",
    "component": "BlockBasic",
    "editComponent": "EditDataMapping",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "dataSource": "table",
      "sources": [],
      "varSourceName": "",
      "dataColumn": "",
      "saveData": false,
      "assignVariable": false,
      "variableName": ""
    },
    "cloud": false
  },
  {
    "id": "sort-data",
    "name": "Sort data",
    "description": "Sort the items of data",
    "icon": "riSortAsc",
    "component": "BlockBasic",
    "editComponent": "EditSortData",
    "category": "data",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "sortByProperty": false,
      "itemProperties": [],
      "dataSource": "table",
      "varSourceName": "",
      "dataColumn": "",
      "saveData": false,
      "assignVariable": false,
      "variableName": ""
    },
    "cloud": false
  },
  {
    "id": "create-element",
    "name": "Create element",
    "description": "Create an element and insert it into the page",
    "icon": "riHtml5Line",
    "component": "BlockBasic",
    "editComponent": "EditCreateElement",
    "category": "interaction",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "html",
      "css",
      "selector"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "javascript": "",
      "html": "",
      "css": "",
      "preloadScripts": [],
      "findBy": "cssSelector",
      "insertAt": "after",
      "runBeforeLoad": false,
      "waitForSelector": false,
      "waitSelectorTimeout": 5000,
      "selector": "body"
    },
    "cloud": false
  },
  {
    "id": "cookie",
    "name": "Cookie",
    "description": "Get, set, or remove cookies",
    "icon": "path:M20.87 10.5C20.6 10 20 10 20 10H18V9C18 8 17 8 17 8H15V7C15 6 14 6 14 6H13V4C13 3 12 3 12 3C7.03 3 3 7.03 3 12C3 16.97 7.03 21 12 21C16.97 21 21 16.97 21 12C21 11.5 20.96 11 20.87 10.5M11.32 18.96C12 18.82 12.5 18.22 12.5 17.5C12.5 16.67 11.83 16 11 16S9.5 16.67 9.5 17.5C9.5 18 9.76 18.47 10.16 18.74C7.54 18.04 5.5 15.81 5.09 13.12C5 12.61 5 12.11 5 11.62C5.07 12.39 5.71 13 6.5 13C7.33 13 8 12.33 8 11.5S7.33 10 6.5 10C5.82 10 5.25 10.46 5.07 11.08C5.47 8 7.91 5.5 11 5.07V6.5C11 7.33 11.67 8 12.5 8H13V8.5C13 9.33 13.67 10 14.5 10H16V10.5C16 11.33 16.67 12 17.5 12H19C19 16.08 15.5 19.36 11.32 18.96M9.5 9C8.67 9 8 8.33 8 7.5S8.67 6 9.5 6 11 6.67 11 7.5 10.33 9 9.5 9M13 12.5C13 13.33 12.33 14 11.5 14S10 13.33 10 12.5 10.67 11 11.5 11 13 11.67 13 12.5M18 14.5C18 15.33 17.33 16 16.5 16S15 15.33 15 14.5 15.67 13 16.5 13 18 13.67 18 14.5Z",
    "component": "BlockBasic",
    "editComponent": "EditCookie",
    "category": "browser",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "domain",
      "expirationDate",
      "path",
      "sameSite",
      "name",
      "url",
      "value",
      "jsonCode",
      "variableName"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "type": "get",
      "jsonCode": "{\n\n}",
      "useJson": false,
      "getAll": false,
      "domain": "",
      "expirationDate": "",
      "path": "",
      "sameSite": "",
      "name": "",
      "url": "",
      "value": "",
      "httpOnly": false,
      "secure": false,
      "session": false,
      "assignVariable": false,
      "variableName": "",
      "saveData": true,
      "dataColumn": ""
    },
    "cloud": false
  },
  {
    "id": "block-package",
    "name": "Block package",
    "description": "Block package",
    "icon": "riHtml5Line",
    "component": "BlockPackage",
    "editComponent": "EditPackage",
    "category": "package",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {},
    "cloud": true
  },
  {
    "id": "note",
    "name": "Note",
    "description": "",
    "icon": "riFileEditLine",
    "component": "BlockNote",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "disableEdit": true,
    "data": {
      "disableBlock": false,
      "note": "",
      "drawing": false,
      "width": 280,
      "height": 168,
      "color": "white",
      "fontSize": "regular"
    },
    "cloud": false
  },
  {
    "id": "workflow-state",
    "name": "Workflow State",
    "description": "Manage workflows states",
    "icon": "riSettings3Line",
    "component": "BlockBasic",
    "editComponent": "EditWorkflowState",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "refDataKeys": [
      "errorMessage"
    ],
    "data": {
      "disableBlock": false,
      "description": "",
      "type": "stop-current",
      "exceptCurrent": false,
      "workflowsToStop": [],
      "throwError": false,
      "errorMessage": ""
    },
    "cloud": false
  },
  {
    "id": "parameter-prompt",
    "name": "Parameter prompt",
    "description": "",
    "icon": "riCommandLine",
    "component": "BlockBasic",
    "editComponent": "EditParameterPrompt",
    "category": "general",
    "inputs": 1,
    "outputs": 1,
    "allowedInputs": true,
    "maxConnection": 1,
    "data": {
      "disableBlock": false,
      "description": "",
      "timeout": 60000,
      "parameters": []
    },
    "cloud": false
  }
]
